export enum ActivityTypeEnum {
  GENERIC_NOTE = 'GENERIC_NOTE',

  GENERIC_FILE = 'GENERIC_FILE',

  GENERIC_REMINDER = 'GENERIC_REMINDER',

  GENERIC_TASK = 'GENERIC_TASK',

  GENERIC_EVENT = 'GENERIC_EVENT',

  GENERIC_EMAIL = 'GENERIC_EMAIL',

  GENERIC_CALL = 'GENERIC_CALL',

  GENERIC_MEETING = 'GENERIC_MEETING',

  GENERIC_VISIT = 'GENERIC_VISIT',

  GENERIC_PAYMENT = 'GENERIC_PAYMENT',

  GENERIC_EXPENSE = 'GENERIC_EXPENSE',

  GENERIC_INVOICE = 'GENERIC_INVOICE',

  GENERIC_RECEIPT = 'GENERIC_RECEIPT',
}
